GraphQL:
  Enabled: true
  Include:
    - "**/graphql/**/*"
  Exclude:
    - "spec/**/*"
    - "test/**/*"

GraphQL/ArgumentDescription:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Ensures all arguments have a description'

GraphQL/ArgumentName:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'This cop checks whether argument names are snake_case'

GraphQL/ArgumentUniqueness:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'This cop enforces arguments to be defined once per block'

GraphQL/ResolverMethodLength:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Checks resolver methods are not too long'
  Max: 10
  CountComments: false
  ExcludedMethods: []

GraphQL/FieldDefinitions:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Checks consistency of field definitions'
  EnforcedStyle: group_definitions
  SupportedStyles:
    - group_definitions
    - define_resolver_after_definition

GraphQL/MultipleFieldDefinitions:
  Enabled: true
  Description: 'Ensures that fields with multiple definitions are grouped together'

GraphQL/FieldDescription:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Ensures all fields have a description'

GraphQL/FieldHashKey:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Checks :hash_key option is used for appropriate fields'

GraphQL/FieldMethod:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Checks :method option is used for appropriate fields'

GraphQL/FieldName:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'This cop checks whether field names are snake_case'
  SafeAutoCorrect: false

GraphQL/FieldUniqueness:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'This cop enforces fields to be defined once'

GraphQL/ExtractInputType:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Suggests using input type instead of many arguments'
  MaxArguments: 2

GraphQL/ExtractType:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Suggests extracting fields with common prefixes to the separate type'
  MaxFields: 2
  Prefixes:
    - is
    - has
    - with
    - avg
    - min
    - max

GraphQL/LegacyDsl:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Checks that types are defined with class-based API'

GraphQL/ObjectDescription:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Ensures all types have a description'
  Exclude:
    - '**/*_schema.rb'
    - '**/base_*.rb'

GraphQL/OrderedArguments:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Arguments should be alphabetically sorted within groups'

GraphQL/OrderedFields:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Fields should be alphabetically sorted within groups'

GraphQL/UnusedArgument:
  Enabled: true
  Description: 'Arguments should either be listed explicitly or **rest should be in the resolve signature'
